baseURL = 'https://divakarpatil.com/'
languageCode = 'en-au' # or en-gb, en-us, ja-jp, etc
title = 'Divakar Patil'
theme = 'papermod'

# Papermod theme settings
[params]
showCodeCopyButtons = true
showReadingTime = true

[params.editPost]
URL = "https://github.com/divakarpatil51/til-blog/blob/main/content"
text = "Suggest Changes"
appendFilePath = true
